using Asp.Versioning.ApiExplorer;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Alza_WebAPI.FilterExtension
{
    //Based on : https://cloudkasten.net/how-to-multiple-api-versions-in-one-codebase/
    /// <summary>
    /// ConfigureApiDocumentationOptions.
    /// </summary>
    public class ConfigureApiDocumentationOptions : IConfigureOptions<SwaggerGenOptions>
    {
        /// <summary>
        /// IApiVersionDescriptionProvider.
        /// </summary>
        private readonly IApiVersionDescriptionProvider _provider;

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigureApiDocumentationOptions"/> class.
        /// </summary>
        /// <param name="provider"></param>
        public ConfigureApiDocumentationOptions(IApiVersionDescriptionProvider provider)
        {
            _provider = provider;
        }

        /// <summary>
        /// Configure number of documenets generated by swagger generator. 
        /// </summary>
        /// <param name="options">The SwaggerGenOptions instance to configure.</param>
        public void Configure(SwaggerGenOptions options)
        {
            foreach ( var description in _provider.ApiVersionDescriptions)
            {
                options.SwaggerDoc(description.GroupName, CreateInfoForApiVersion(description));
            }
        }

        /// <summary>
        /// Create OpenApiInfo filled with api description.
        /// </summary>
        /// <param name="description">ApiVersionDescription.</param>
        /// <returns>Returns filled OpenApiInfo.</returns>
        private static OpenApiInfo CreateInfoForApiVersion(ApiVersionDescription description)
        {
            var info = new OpenApiInfo()
            {
                Title = "AlzaWebAPI",
                Version = description.ApiVersion.ToString(),
            };
            if(description.IsDeprecated)
            {
                info.Description += "Deprecated version";
            }
            return info;
        }
    }
}
